### ISSUE TITLE
Desired State for Stored Procedures?

### ISSUE THREAD

**Issue by mreishus** [jdaigle/Horton#3]
Does Horton support desired state for stored procedures?  If so, could a quick example of this be added to the documentations?

I thought it did, from reading [this blog post](http://josephdaigle.me/2016/04/02/database-versioning-showdown.html), but I tried and I can't get it to work.

Here's what I did:
- I added Horton.exe 4.0.0 to my project root dir and wrote a ps1 script to run it across my DB.
- I added a "Migrations_Horton" directory.
- Inside that directory, I included a "StoredProcedures" directory.
- Inside there, I added [uspGetBillOfMaterials.sql](https://github.com/jdaigle/Horton/blob/f432b88a0/samples/AdventureWorks2014/StoredProcedures/uspGetBillOfMaterials.sql), copied from commit f432b88a0.

Then:
- I ran `Horton.exe UPDATE` which did create the proc on my db!  Success. :white_check_mark: 
- Eliminate drift check:  I modified the proc directly on the SQL server using SSMS.   I ran `Horton.exe UPDATE` and expected horton to bring the proc back to the committed state.  It didn't.  I also tried SYNC.
- Update check:  I edited the uspGetBillOfMaterials.sql on disk and re-ran `Horton.exe UPDATE`.  It didn't change anything, I still had the version I manually edited on the server.  I also tried SYNC.  Still nothing.

Unless I'm missing something major here, it seems that horton no longer supports desired state for stored procedures?  Am I doing anything wrong or was this removed in the 4.0 release?

**Comment by mreishus** [comment]
It seems that there isn't support for it... I added support for it here: https://github.com/jdaigle/Horton/pull/4  

It's kinda hacky, but it works.

**Comment by jdaigle** [comment]
@mreishus Thank you very much for this bug report. Horton is definitely _supposed to_ support re-running "repeatable" scripts like sprocs/views/etc. I think that as part of rewriting it for 4.x, that feature didn't get fully testing. But I've just pushed the fix and will shortly create a new release.

**Comment by mreishus** [comment]
Thanks for the quick response!  In the new version - repeated updates are working.  As long as I modify `uspGetBillOfMaterials.sql` in my source repo, horton will apply it again.   

However, drift is not eliminated.  If I run horton, then manually change the definition of a proc on the sql server, then run horton again, the second run does nothing because the `.sql` file hasn't changed.  I would expect it to change the proc back to what's in the `.sql` file.. what do you think?

**Comment by jdaigle** [comment]
@mreishus Horton doesn't compare the schema of the actual database. It only detects when the file has changed.

The principle behind Horton is that database changes are executed via migrations managed by Horton.
